version: '3'
services:
  app:
    build:
      target: development
    volumes:
      - .:/app
  db:
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
  redis:
    volumes:
      - ./storage/redis:/data
